<!doctype html>
<html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><title>WooCommerce إلى سلة</title><style>
*{box-sizing:border-box}body{font-family:system-ui;margin:0;background:#f5f7fa;color:#172033}.wrap{max-width:1180px;margin:36px auto;padding:20px}.card{background:#fff;border:1px solid #e5e7eb;border-radius:18px;padding:22px;margin:16px 0;box-shadow:0 8px 28px #0001}.muted{color:#6b7280}.row{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:14px 0}.stat{padding:14px;border-radius:12px;background:#f8fafc;border:1px solid #e5e7eb}.stat b{display:block;font-size:22px}input,button,select{font:inherit;padding:11px;border-radius:10px;border:1px solid #d1d5db}input[type=text],input[type=password],input[type=url]{width:100%;margin:6px 0}button,.btn{background:#111827;color:#fff;border:0;cursor:pointer;text-decoration:none;padding:11px 16px;border-radius:10px}button:disabled{opacity:.45;cursor:not-allowed}.secondary{background:#eef2f7;color:#172033}.danger{background:#991b1b}.item{border-top:1px solid #edf0f3;padding:14px 0}.item:first-child{border-top:0}.badge{display:inline-block;font-size:12px;padding:5px 8px;border-radius:999px;background:#eef2f7;margin:3px}.failed{background:#fee2e2;color:#991b1b}.completed{background:#dcfce7;color:#166534}.processing,.importing,.scanning{background:#dbeafe;color:#1d4ed8}.hidden{display:none}.error{color:#991b1b;white-space:pre-wrap;font-size:13px}.empty{text-align:center;padding:24px;color:#6b7280}.selectbox{width:20px;height:20px}.toolbar{padding:12px;background:#f8fafc;border:1px solid #e5e7eb;border-radius:12px;margin:12px 0}.pager{display:flex;justify-content:space-between;align-items:center;margin-top:14px}.notice{padding:12px;border-radius:10px;background:#fff7ed;border:1px solid #fed7aa;color:#9a3412}@media(max-width:760px){.grid,.stats{grid-template-columns:1fr}.pager{align-items:stretch;gap:8px;flex-direction:column}}
</style></head><body><main class="wrap"><div class="row" style="justify-content:space-between"><div><h1>نقل منتجات WooCommerce إلى سلة</h1><div class="muted">إدارة الاستيراد والأخطاء وإعادة المحاولة.</div></div><button id="refresh" class="secondary">تحديث</button></div>
@if(!session('salla_merchant_id'))
<section class="card"><h2>ربط متجر سلة</h2><p class="muted">ابدأ بتفويض التطبيق للوصول إلى متجرك.</p><a class="btn" href="{{ route('salla.oauth.redirect') }}">ربط سلة</a></section>
@else
<section class="card"><h2>ربط WooCommerce</h2><form id="woo"><input name="store_url" type="url" placeholder="https://store.example.com" required><div class="grid"><input name="consumer_key" placeholder="Consumer Key" required><input name="consumer_secret" type="password" placeholder="Consumer Secret" required></div><div class="row"><button>اختبار وحفظ الاتصال</button><span id="woo-result" class="muted"></span></div></form></section>
<section class="card"><h2>المتاجر المتصلة</h2><div id="connections"><div class="empty">جاري التحميل...</div></div></section>
<section class="card"><h2>عمليات الاستيراد</h2><div id="imports"><div class="empty">جاري التحميل...</div></div></section>
<section id="report" class="card hidden"><div class="row" style="justify-content:space-between"><div><h2 id="report-title">المنتجات</h2><div id="report-meta" class="muted"></div></div><button id="close-report" class="secondary">إغلاق</button></div><div id="report-stats" class="stats"></div><div class="notice">لن يبدأ نقل أي منتج تلقائيًا. حدّد المنتجات المطلوبة أولًا ثم اضغط «نقل المحدد».</div><div class="toolbar row"><select id="status-filter"><option value="">كل الحالات</option><option value="failed">فاشل</option><option value="processing">قيد المعالجة</option><option value="pending">بانتظار التنفيذ</option><option value="completed">مكتمل</option></select><input id="product-search" type="text" placeholder="بحث بالاسم أو SKU أو Woo ID" style="max-width:320px"><button id="search-products" class="secondary">بحث</button><button id="select-page" class="secondary">تحديد القابل للنقل في الصفحة</button><button id="clear-selection" class="secondary">إلغاء التحديد</button></div><div class="row" style="justify-content:space-between"><div><b>المحدد: <span id="selected-count">0</span></b><div class="muted">يمكن تحديد حتى 500 منتج في العملية الواحدة.</div></div><div class="row"><button id="run-selected" disabled>نقل المحدد</button><button id="retry-report" class="danger">إعادة كل الفاشلة</button></div></div><div id="products"></div><div class="pager"><button id="prev-page" class="secondary">السابق</button><span id="page-meta" class="muted"></span><button id="next-page" class="secondary">التالي</button></div></section>
<p id="message" class="muted"></p>
<script>
const csrf=document.querySelector('meta[name=csrf-token]').content;let dash=null,active=null,timer=null,page=1,lastPage=1,selected=new Set();const L={scanning:'جاري الفحص',scanned:'جاهز للاختيار',importing:'جاري النقل',partial:'مكتمل جزئياً',completed:'مكتمل',failed:'فشل',pending:'بانتظار التنفيذ',processing:'قيد المعالجة'};const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const lab=v=>L[v]||v||'-';
async function req(url,opt={}){opt.headers={...(opt.headers||{}),Accept:'application/json','X-CSRF-TOKEN':csrf};const r=await fetch(url,opt),j=await r.json().catch(()=>({}));if(!r.ok){const detail=j.errors?Object.values(j.errors).flat().join(' '):j.message;throw new Error(detail||'تعذر تنفيذ الطلب')}return j}function msg(t){document.querySelector('#message').textContent=t}
async function load(){try{dash=await req('/api/v1/dashboard');render();schedule()}catch(e){msg(e.message)}}
function render(){const cs=dash.connections||[],is=dash.imports||[];document.querySelector('#connections').innerHTML=cs.length?cs.map(c=>`<div class="item"><div class="row" style="justify-content:space-between"><div><b>${esc(c.store_url)}</b><div class="muted">${esc(lab(c.status))}</div></div><button onclick="createImport(${Number(c.id)})">فحص الكتالوج</button></div></div>`).join(''):'<div class="empty">لا يوجد متجر متصل.</div>';document.querySelector('#imports').innerHTML=is.length?is.map(i=>`<div class="item"><div class="row" style="justify-content:space-between"><div><b>عملية ${esc(String(i.id).slice(0,8))}</b><div><span class="badge ${esc(i.status)}">${esc(lab(i.status))}</span><span class="badge">الإجمالي ${Number(i.total_products||0)}</span><span class="badge completed">المكتمل ${Number(i.completed_products||0)}</span><span class="badge failed">الفاشل ${Number(i.failed_products||0)}</span></div></div><div class="row"><button onclick="openReport('${esc(i.id)}')">${['scanned','partial','failed'].includes(i.status)?'اختيار المنتجات':'التقرير'}</button>${Number(i.failed_products||0)>0?`<button class="danger" onclick="retryFailed('${esc(i.id)}')">إعادة الفاشلة</button>`:''}</div></div></div>`).join(''):'<div class="empty">لا توجد عمليات استيراد.</div>'}
async function createImport(id){try{const j=await req('/api/v1/imports',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({woocommerce_connection_id:id})});msg('بدأ فحص الكتالوج');active=j.id;selected.clear();await load()}catch(e){msg(e.message)}}
async function runSelected(){if(!active||selected.size===0)return;if(selected.size>500){msg('الحد الأقصى 500 منتج في الدفعة الواحدة');return}if(!confirm(`سيتم نقل ${selected.size} منتج محدد فقط. متابعة؟`))return;try{const ids=[...selected];const j=await req(`/api/v1/imports/${active}/run`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({product_ids:ids})});selected.clear();syncSelection();msg(`تمت جدولة ${j.queued} منتج محدد`);await load();await loadReport()}catch(e){msg(e.message)}}
async function retryFailed(id){if(!confirm('سيتم إعادة محاولة جميع المنتجات الفاشلة في هذه العملية. متابعة؟'))return;try{const j=await req(`/api/v1/imports/${id}/retry-failed`,{method:'POST'});msg(`تمت إعادة جدولة ${j.queued} منتج فاشل`);await load();if(active===id)await loadReport()}catch(e){msg(e.message)}}
async function openReport(id){active=id;page=1;selected.clear();syncSelection();document.querySelector('#report').classList.remove('hidden');document.querySelector('#status-filter').value='';document.querySelector('#product-search').value='';await loadReport();document.querySelector('#report').scrollIntoView({behavior:'smooth'})}
async function loadReport(){if(!active)return;try{const f=document.querySelector('#status-filter').value,q=document.querySelector('#product-search').value.trim(),params=new URLSearchParams({page:String(page),per_page:'50'});if(f)params.set('status',f);if(q)params.set('q',q);const j=await req(`/api/v1/imports/${active}?${params}`),s=j.summary||{},p=j.products||{};page=Number(p.current_page||1);lastPage=Number(p.last_page||1);document.querySelector('#report-title').textContent=`منتجات العملية ${String(j.import.id).slice(0,8)}`;document.querySelector('#report-meta').textContent=`الحالة: ${lab(j.import.status)} · عرض ${Number(p.from||0)}-${Number(p.to||0)} من ${Number(p.total||0)}`;document.querySelector('#report-stats').innerHTML=[['مكتمل',s.completed],['فاشل',s.failed],['قيد المعالجة',s.processing],['بانتظار التنفيذ',s.pending]].map(x=>`<div class="stat"><span class="muted">${x[0]}</span><b>${Number(x[1]||0)}</b></div>`).join('');document.querySelector('#retry-report').disabled=!Number(s.failed||0);const rows=p.data||[];document.querySelector('#products').innerHTML=rows.length?rows.map(x=>{const eligible=['pending','failed'].includes(x.import_status),checked=selected.has(x.id)?'checked':'';return `<div class="item"><div class="row" style="align-items:flex-start"><input class="selectbox product-check" type="checkbox" data-id="${esc(x.id)}" ${eligible?'': 'disabled'} ${checked}><div style="flex:1"><b>${esc(x.name)}</b><div class="muted">SKU: ${esc(x.sku||'-')} · Woo #${esc(x.source_product_id)}${x.destination_product_id?' · Salla #'+esc(x.destination_product_id):''}</div><div><span class="badge ${esc(x.import_status)}">${esc(lab(x.import_status))}</span><span class="badge">التحقق: ${esc(x.verification_status)}</span><span class="badge">الخطوة: ${esc(x.current_step||'-')}</span></div>${x.last_error?`<div class="error">${esc(x.last_error)}</div>`:''}</div></div></div>`}).join(''):'<div class="empty">لا توجد منتجات.</div>';document.querySelectorAll('.product-check').forEach(el=>el.onchange=()=>{el.checked?selected.add(el.dataset.id):selected.delete(el.dataset.id);syncSelection()});document.querySelector('#prev-page').disabled=page<=1;document.querySelector('#next-page').disabled=page>=lastPage;document.querySelector('#page-meta').textContent=`صفحة ${page} من ${lastPage}`;syncSelection()}catch(e){msg(e.message)}}
function syncSelection(){document.querySelector('#selected-count').textContent=selected.size;document.querySelector('#run-selected').disabled=selected.size===0||selected.size>500}
function schedule(){clearTimeout(timer);if((dash.imports||[]).some(i=>['scanning','importing'].includes(i.status)))timer=setTimeout(async()=>{await load();if(active)await loadReport()},4000)}
document.querySelector('#woo').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target),r=document.querySelector('#woo-result');r.textContent='جاري الاختبار...';try{await req('/api/v1/woocommerce/connections',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(f))});r.textContent='تم الربط بنجاح';e.target.reset();await load()}catch(x){r.textContent=x.message}});document.querySelector('#refresh').onclick=async()=>{await load();if(active)await loadReport()};document.querySelector('#close-report').onclick=()=>{active=null;selected.clear();document.querySelector('#report').classList.add('hidden')};document.querySelector('#status-filter').onchange=()=>{page=1;loadReport()};document.querySelector('#search-products').onclick=()=>{page=1;loadReport()};document.querySelector('#product-search').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();page=1;loadReport()}};document.querySelector('#retry-report').onclick=()=>active&&retryFailed(active);document.querySelector('#run-selected').onclick=runSelected;document.querySelector('#clear-selection').onclick=()=>{selected.clear();document.querySelectorAll('.product-check').forEach(x=>x.checked=false);syncSelection()};document.querySelector('#select-page').onclick=()=>{document.querySelectorAll('.product-check:not(:disabled)').forEach(x=>{if(selected.size<500){selected.add(x.dataset.id);x.checked=true}});syncSelection()};document.querySelector('#prev-page').onclick=()=>{if(page>1){page--;loadReport()}};document.querySelector('#next-page').onclick=()=>{if(page<lastPage){page++;loadReport()}};load();
</script>
@endif
</main></body></html>
