<!doctype html>
<html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><title>WooCommerce إلى سلة</title><style>
*{box-sizing:border-box}body{font-family:system-ui;margin:0;background:#f5f7fa;color:#172033}.wrap{max-width:1180px;margin:36px auto;padding:20px}.card{background:#fff;border:1px solid #e5e7eb;border-radius:18px;padding:22px;margin:16px 0;box-shadow:0 8px 28px #0001}.muted{color:#6b7280}.row{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:14px 0}.stat{padding:14px;border-radius:12px;background:#f8fafc;border:1px solid #e5e7eb}.stat b{display:block;font-size:22px}input,button,select{font:inherit;padding:11px;border-radius:10px;border:1px solid #d1d5db}input{width:100%;margin:6px 0}button,.btn{background:#111827;color:#fff;border:0;cursor:pointer;text-decoration:none;padding:11px 16px;border-radius:10px}.secondary{background:#eef2f7;color:#172033}.danger{background:#991b1b}.item{border-top:1px solid #edf0f3;padding:14px 0}.item:first-child{border-top:0}.badge{display:inline-block;font-size:12px;padding:5px 8px;border-radius:999px;background:#eef2f7;margin:3px}.failed{background:#fee2e2;color:#991b1b}.completed{background:#dcfce7;color:#166534}.processing,.importing,.scanning{background:#dbeafe;color:#1d4ed8}.hidden{display:none}.error{color:#991b1b;white-space:pre-wrap;font-size:13px}.empty{text-align:center;padding:24px;color:#6b7280}@media(max-width:760px){.grid,.stats{grid-template-columns:1fr}}
</style></head><body><main class="wrap"><div class="row" style="justify-content:space-between"><div><h1>نقل منتجات WooCommerce إلى سلة</h1><div class="muted">إدارة الاستيراد والأخطاء وإعادة المحاولة.</div></div><button id="refresh" class="secondary">تحديث</button></div>
@if(!session('salla_merchant_id'))
<section class="card"><h2>ربط متجر سلة</h2><p class="muted">ابدأ بتفويض التطبيق للوصول إلى متجرك.</p><a class="btn" href="{{ route('salla.oauth.redirect') }}">ربط سلة</a></section>
@else
<section class="card"><h2>ربط WooCommerce</h2><form id="woo"><input name="store_url" placeholder="https://store.example.com" required><div class="grid"><input name="consumer_key" placeholder="Consumer Key" required><input name="consumer_secret" type="password" placeholder="Consumer Secret" required></div><div class="row"><button>اختبار وحفظ الاتصال</button><span id="woo-result" class="muted"></span></div></form></section>
<section class="card"><h2>المتاجر المتصلة</h2><div id="connections"><div class="empty">جاري التحميل...</div></div></section>
<section class="card"><h2>عمليات الاستيراد</h2><div id="imports"><div class="empty">جاري التحميل...</div></div></section>
<section id="report" class="card hidden"><div class="row" style="justify-content:space-between"><div><h2 id="report-title">تقرير الاستيراد</h2><div id="report-meta" class="muted"></div></div><button id="close-report" class="secondary">إغلاق</button></div><div id="report-stats" class="stats"></div><div class="row"><select id="status-filter"><option value="">كل المنتجات</option><option value="failed">فاشل</option><option value="processing">قيد المعالجة</option><option value="pending">بانتظار التنفيذ</option><option value="completed">مكتمل</option></select><button id="retry-report" class="danger">إعادة الفاشلة</button></div><div id="products"></div></section>
<p id="message" class="muted"></p>
<script>
const csrf=document.querySelector('meta[name=csrf-token]').content;let dash=null,active=null,timer=null;const L={scanning:'جاري الفحص',scanned:'جاهز للنقل',importing:'جاري النقل',partial:'مكتمل جزئياً',completed:'مكتمل',failed:'فشل',pending:'بانتظار التنفيذ',processing:'قيد المعالجة'};const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const lab=v=>L[v]||v||'-';
async function req(url,opt={}){opt.headers={...(opt.headers||{}),Accept:'application/json','X-CSRF-TOKEN':csrf};const r=await fetch(url,opt),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.message||'تعذر تنفيذ الطلب');return j}function msg(t){document.querySelector('#message').textContent=t}
async function load(){try{dash=await req('/api/v1/dashboard');render();schedule()}catch(e){msg(e.message)}}
function render(){const cs=dash.connections||[],is=dash.imports||[];document.querySelector('#connections').innerHTML=cs.length?cs.map(c=>`<div class="item"><div class="row" style="justify-content:space-between"><div><b>${esc(c.store_url)}</b><div class="muted">${esc(lab(c.status))}</div></div><button onclick="createImport(${Number(c.id)})">فحص الكتالوج</button></div></div>`).join(''):'<div class="empty">لا يوجد متجر متصل.</div>';document.querySelector('#imports').innerHTML=is.length?is.map(i=>`<div class="item"><div class="row" style="justify-content:space-between"><div><b>عملية ${esc(String(i.id).slice(0,8))}</b><div><span class="badge ${esc(i.status)}">${esc(lab(i.status))}</span><span class="badge">الإجمالي ${Number(i.total_products||0)}</span><span class="badge completed">المكتمل ${Number(i.completed_products||0)}</span><span class="badge failed">الفاشل ${Number(i.failed_products||0)}</span></div></div><div class="row"><button class="secondary" onclick="openReport('${esc(i.id)}')">التقرير</button>${['scanned','partial','failed'].includes(i.status)?`<button onclick="runImport('${esc(i.id)}')">${i.status==='scanned'?'بدء النقل':'استكمال'}</button>`:''}${Number(i.failed_products||0)>0?`<button class="danger" onclick="retryFailed('${esc(i.id)}')">إعادة الفاشلة</button>`:''}</div></div></div>`).join(''):'<div class="empty">لا توجد عمليات استيراد.</div>'}
async function createImport(id){try{const j=await req('/api/v1/imports',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({woocommerce_connection_id:id})});msg('بدأ فحص الكتالوج');active=j.id;await load()}catch(e){msg(e.message)}}async function runImport(id){try{const j=await req(`/api/v1/imports/${id}/run`,{method:'POST'});msg(`تمت جدولة ${j.queued} منتج`);await load();if(active===id)await loadReport()}catch(e){msg(e.message)}}async function retryFailed(id){try{const j=await req(`/api/v1/imports/${id}/retry-failed`,{method:'POST'});msg(`تمت إعادة جدولة ${j.queued} منتج فاشل`);await load();if(active===id)await loadReport()}catch(e){msg(e.message)}}
async function openReport(id){active=id;document.querySelector('#report').classList.remove('hidden');document.querySelector('#status-filter').value='';await loadReport();document.querySelector('#report').scrollIntoView({behavior:'smooth'})}async function loadReport(){if(!active)return;try{const f=document.querySelector('#status-filter').value,j=await req(`/api/v1/imports/${active}${f?'?status='+encodeURIComponent(f):''}`),s=j.summary||{};document.querySelector('#report-title').textContent=`تقرير ${String(j.import.id).slice(0,8)}`;document.querySelector('#report-meta').textContent=`الحالة: ${lab(j.import.status)}`;document.querySelector('#report-stats').innerHTML=[['مكتمل',s.completed],['فاشل',s.failed],['قيد المعالجة',s.processing],['بانتظار التنفيذ',s.pending]].map(x=>`<div class="stat"><span class="muted">${x[0]}</span><b>${Number(x[1]||0)}</b></div>`).join('');document.querySelector('#retry-report').disabled=!Number(s.failed||0);const rows=j.products?.data||[];document.querySelector('#products').innerHTML=rows.length?rows.map(p=>`<div class="item"><b>${esc(p.name)}</b><div class="muted">SKU: ${esc(p.sku||'-')} · Woo #${esc(p.source_product_id)}${p.destination_product_id?' · Salla #'+esc(p.destination_product_id):''}</div><div><span class="badge ${esc(p.import_status)}">${esc(lab(p.import_status))}</span><span class="badge">التحقق: ${esc(p.verification_status)}</span><span class="badge">الخطوة: ${esc(p.current_step||'-')}</span></div>${p.last_error?`<div class="error">${esc(p.last_error)}</div>`:''}</div>`).join(''):'<div class="empty">لا توجد منتجات.</div>'}catch(e){msg(e.message)}}
function schedule(){clearTimeout(timer);if((dash.imports||[]).some(i=>['scanning','importing'].includes(i.status)))timer=setTimeout(async()=>{await load();if(active)await loadReport()},4000)}document.querySelector('#woo').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target),r=document.querySelector('#woo-result');r.textContent='جاري الاختبار...';try{await req('/api/v1/woocommerce/connections',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(f))});r.textContent='تم الربط بنجاح';e.target.reset();await load()}catch(x){r.textContent=x.message}});document.querySelector('#refresh').onclick=async()=>{await load();if(active)await loadReport()};document.querySelector('#close-report').onclick=()=>{active=null;document.querySelector('#report').classList.add('hidden')};document.querySelector('#status-filter').onchange=loadReport;document.querySelector('#retry-report').onclick=()=>active&&retryFailed(active);load();
</script>
@endif
</main></body></html>
