<?php

declare(strict_types=1);

namespace App\Http\Controllers;
use App\Integrations\WooCommerce\SafeStoreUrl;use App\Models\Merchant;use App\Models\WooCommerceConnection;use Illuminate\Http\JsonResponse;use Illuminate\Http\RedirectResponse;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Support\Str;
final class WooCommerceAuthController extends Controller
{
 public function start(Request $request):RedirectResponse{$merchant=$request->attributes->get('merchant');abort_unless($merchant instanceof Merchant,401);$data=$request->validate(['store_url'=>['required','url','max:2048']]);$url=rtrim($data['store_url'],'/');SafeStoreUrl::assert($url);$nonce=Str::random(64);DB::table('woocommerce_auth_requests')->insert(['nonce_hash'=>hash('sha256',$nonce),'merchant_id'=>$merchant->id,'store_url'=>$url,'expires_at'=>now()->addMinutes(15),'created_at'=>now(),'updated_at'=>now()]);$query=http_build_query(['app_name'=>'WooCommerce to Salla','scope'=>'read','user_id'=>$nonce,'return_url'=>url('/'),'callback_url'=>route('woo.auth.callback')]);return redirect()->away($url.'/wc-auth/v1/authorize?'.$query);}
 public function callback(Request $request):JsonResponse{$data=$request->validate(['key_id'=>['required'],'user_id'=>['required','string'],'consumer_key'=>['required','string'],'consumer_secret'=>['required','string'],'key_permissions'=>['required','string']]);$pending=DB::table('woocommerce_auth_requests')->where('nonce_hash',hash('sha256',$data['user_id']))->whereNull('used_at')->where('expires_at','>',now())->first();abort_unless($pending,403,'Unknown or expired WooCommerce authorization.');abort_unless(in_array($data['key_permissions'],['read','read_write'],true),422,'WooCommerce key must allow read access.');WooCommerceConnection::query()->updateOrCreate(['merchant_id'=>$pending->merchant_id,'store_hash'=>hash('sha256',strtolower($pending->store_url))],['store_url'=>$pending->store_url,'consumer_key'=>$data['consumer_key'],'consumer_secret'=>$data['consumer_secret'],'status'=>'connected','last_verified_at'=>now()]);DB::table('woocommerce_auth_requests')->where('id',$pending->id)->update(['used_at'=>now(),'updated_at'=>now()]);return response()->json(['received'=>true]);}
}
